name: Build sbnb

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-large

    steps:
    - uses: actions/checkout@v4

    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Output Run Attempt
      run: echo ${{ github.run_attempt }}

    - name: Install dependencies
      run: |
        # Need for /usr/lib/systemd/boot/efi/linuxx64.efi.stub, qemu-img
        sudo apt-get update
        sudo apt-get install -y systemd-boot-efi qemu-utils
    
    - name: git submodule init and update
      run: |
        git submodule init
        git submodule update
        
    - name: Buildroot CCache
      # Restoring and saving cache using a single action
      uses: actions/cache@v4
      with:
        path: ~/.buildroot-ccache
        key: buildroot-ccache

    - name: Buildroot output cache
      # Restoring and saving cache using a single action
      uses: actions/cache@v4
      with:
        path: |
          buildroot/output/build
          buildroot/output/host
          buildroot/output/staging
          buildroot/output/target
        key: buildroot-output

    - name: Configure
      run: |
        cd buildroot
        make BR2_EXTERNAL=.. sbnb_defconfig

    - name: Run make
      run: |
        cd buildroot
        make -j $(nproc)
        
    - name: Save sbnb images
      uses: actions/upload-artifact@v4
      with:
        name: sbnb-images
        path: |
          buildroot/output/images/sbnb.raw.gz
          buildroot/output/images/sbnb.vhd
          buildroot/output/images/sbnb.efi
